version: "3"

services:
  nginx-angular:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
       - "8081:80"
    expose:
       - "8081"
  keycloak:
    container_name: keycloak
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    volumes:
      - ./keycloak/realms-export.json:/opt/keycloak/data/import/realms-export.json
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=singleFile"
      - "-Dkeycloak.migration.file=/opt/keycloak/data/import/realms-export.json"
      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
      - start-dev
    ports:
      - 8080:8080
