version: "3"

services:
  nginx-angular:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
       - "8081:80"
    expose:
       - "8081"
  keycloak:
    container_name: keycloak
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled
    command: 
      - start-dev
      - --import-realm
    ports:
      - 8080:8080
